services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GeorgRinger\Eventnews\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  GeorgRinger\Eventnews\Update\UpdatePluginFlexforms:
    public: true
